# Alfresco Enterprise ACS Deployment AWS
# Copyright (C) 2005 - 2018 Alfresco Software Limited
# License rights for this program may be obtained from Alfresco Software, Ltd.
# pursuant to a written agreement and any use of this program without such an
# agreement is prohibited.

AWSTemplateFormatVersion: "2010-09-09"
Description: "EFS stack that deploys EFS and sets mountpoints in existent subnets."

Metadata:
    AWS::CloudFormation::Interface:
      ParameterGroups:
        - Label:
            default: EFS Stack Configuration
          Parameters:
            - SecurityGroup
            - NumberOfPrivateSubnets
            - PrivateSubnetIDs

      ParameterLabels:
        SecurityGroup:
          default: The Security Group ID to use for EFS
        NumberOfPrivateSubnets:
          default: Number of private subnets
        PrivateSubnetIDs:
          default: Private subnet IDs

Parameters:
    SecurityGroup:
      Description: "ID for the VPC, This will be used to get the default security group"
      Type: "AWS::EC2::SecurityGroup::Id"
    NumberOfPrivateSubnets:
      Description: The number of private subnets, this must match the number of subnets selected in SubnetIDs parameter.
      Type: String
      Default: "2"
      AllowedValues:
        - "2"
        - "3"
    PrivateSubnetIDs:
      Description: List of private subnet IDs to use
      Type: List<AWS::EC2::Subnet::Id>

Conditions:
  UseThirdSubnet: !Equals [!Ref "NumberOfPrivateSubnets", "3"]

Resources:
  Filesystem:
    Type: AWS::EFS::FileSystem
    Properties: 
      Encrypted: true
      FileSystemTags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-k8s-efs" 
      PerformanceMode: "generalPurpose"

  MountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref Filesystem
      SecurityGroups:
        - !Ref SecurityGroup
      SubnetId: !Select [ 0, !Ref PrivateSubnetIDs ]

  MountTarget2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref Filesystem
      SecurityGroups:
        - !Ref SecurityGroup
      SubnetId: !Select [ 1, !Ref PrivateSubnetIDs ]

  MountTarget3:
    Condition: UseThirdSubnet
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref Filesystem
      SecurityGroups:
        - !Ref SecurityGroup
      SubnetId: !Select [ 2, !Ref PrivateSubnetIDs ]

  NFSIngressRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties: 
      Description: "NFS used for Persistent volume claims in k8s"
      GroupId: !Ref SecurityGroup
      IpProtocol: tcp
      FromPort: 2049
      ToPort: 2049
      SourceSecurityGroupId: !Ref SecurityGroup

Outputs:
  SubstackName:
    Value: !Sub "${AWS::StackName}" 
  EFSId:
    Value: !Ref Filesystem
  EFSName:
    Value: !Sub "${Filesystem}.efs.${AWS::Region}.amazonaws.com"
  MountTargets:
    Value: !Join
      - ","
      - - !Ref MountTarget1
        - !Ref MountTarget2
        - !If
            - UseThirdSubnet
            - !Ref MountTarget3
            - !Ref AWS::NoValue